'use client';
import { createContext, useContext, useState } from 'react';

export const languages = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം', flag: '🇮🇳' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', flag: '🇮🇳' },
];

export const translations = {
  en: {
    // Sidebar
    dashboard: 'Dashboard',
    cropHealth: 'Crop Health',
    resources: 'Resources',
    advisory: 'Advisory',
    orchestration: 'Orchestration',
    evaluation: 'Evaluation',
    edgeDeploy: 'Edge Deploy',
    systemStatus: 'System Status',
    cropAI: 'Crop AI',
    marketFeed: 'Market Feed',
    weatherAPI: 'Weather API',
    ragEngine: 'RAG Engine',
    selectLanguage: 'Select Language',
    // Dashboard
    liveDashboard: '🌿 Live Dashboard',
    commandCenter: 'Command Center',
    dashboardSubtitle: 'Multi-agent AI system for your rubber plantation · Thiruvananthapuram, Kerala · March 4, 2026',
    farmHealthScore: 'Farm Health Score',
    totalTrees: 'Total Trees',
    totalTreesSub: 'Productive area: 4.8 acres',
    dailyLatex: 'Daily Latex (kg)',
    dailyLatexSub: 'Target: 42 kg/day',
    revenue: 'Revenue (Mar)',
    revenueSub: 'Previous: ₹61,200',
    diseaseAlerts: 'Disease Alerts',
    diseaseAlertsSub: '2 active, 1 resolved',
    yieldPerformance: 'Yield Performance',
    yieldSubtitle: 'kg/day vs target',
    activeAlerts: '🔴 Active Alerts',
    viewAll: 'View All →',
    aiAgents: 'AI Agents',
    aiAgentsSubtitle: 'Click any agent to access its full dashboard',
    agentActivityFeed: '⚡ Agent Activity Feed',
    fiveDayForecast: '🌤️ 5-Day Forecast',
    fullReport: 'Full Report →',
    tappingAdvisory: '⚠️ Tapping Advisory',
    tappingAdvisoryText: 'Heavy rainfall expected Friday–Saturday. Suspend morning tapping operations. Resume Sunday.',
    // Agent cards
    cropHealthAgent: 'Crop Health Agent',
    cropHealthDesc: 'AI-powered disease detection via CNN/ViT models on uploaded leaf photos',
    cropHealthStat: '98.2% accuracy',
    resourceAgent: 'Resource Agent',
    resourceDesc: 'Smart irrigation, fertilizer scheduling & soil health optimization',
    resourceStat: '22% water saved',
    weatherAgent: 'Weather Agent',
    weatherDesc: 'Rainfall prediction, tapping schedule & irrigation advisory',
    weatherStat: 'Next rain: Fri',
    advisoryAgent: 'Advisory Agent',
    advisoryDesc: 'LLM + RAG powered multilingual chat in Malayalam & English',
    advisoryStat: 'RAG powered',
    // Activity feed
    act1: 'Advisory Agent recommended nitrogen top-dressing for Block 4',
    act2: 'Resource Agent optimized irrigation – saved 340L today',
    act3: 'RSS price rose to ₹178/kg – Market Agent alert triggered',
    act4: 'Weather Agent: Heavy rain predicted – tapping suspended',
    act5: 'Crop Health scan completed for Zone A – 3 trees flagged',
    ago: 'ago',
    // Disease alerts
    zone1: 'Zone A – Block 3',
    zone2: 'Zone B – Block 7',
    zone3: 'Zone C – Block 1',
    disease1: 'Powdery Mildew',
    disease2: 'Leaf Fall Disease',
    disease3: 'Pink Disease',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
  },

  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    cropHealth: 'വിള ആരോഗ്യം',
    resources: 'വിഭവങ്ങൾ',
    advisory: 'ഉപദേശം',
    orchestration: 'ഓർക്കസ്ട്രേഷൻ',
    evaluation: 'മൂല്യനിർണ്ണയം',
    edgeDeploy: 'എഡ്ജ് ഡിപ്ലോയ്',
    systemStatus: 'സിസ്റ്റം സ്റ്റാറ്റസ്',
    cropAI: 'ക്രോപ്പ് AI',
    marketFeed: 'മാർക്കറ്റ് ഫീഡ്',
    weatherAPI: 'കാലാവസ്ഥ API',
    ragEngine: 'RAG എഞ്ചിൻ',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    liveDashboard: '🌿 തൽസമയ ഡാഷ്‌ബോർഡ്',
    commandCenter: 'കമാൻഡ് സെന്റർ',
    dashboardSubtitle: 'റബ്ബർ തോട്ടത്തിനായി മൾട്ടി-ഏജൻ്റ് AI സിസ്റ്റം · തിരുവനന്തപുരം, കേരള',
    farmHealthScore: 'ഫാം ആരോഗ്യ സ്കോർ',
    totalTrees: 'ആകെ മരങ്ങൾ',
    totalTreesSub: 'ഉൽപ്പാദന വിസ്തീർണ്ണം: 4.8 ഏക്കർ',
    dailyLatex: 'ദൈനംദിന ലാറ്റക്സ് (കിലോ)',
    dailyLatexSub: 'ലക്ഷ്യം: 42 കിലോ/ദിവസം',
    revenue: 'വരുമാനം (മാർ)',
    revenueSub: 'മുൻ: ₹61,200',
    diseaseAlerts: 'രോഗ അലേർട്ടുകൾ',
    diseaseAlertsSub: '2 സജീവം, 1 പരിഹരിച്ചു',
    yieldPerformance: 'ഉൽപ്പാദന പ്രകടനം',
    yieldSubtitle: 'കിലോ/ദിവസം vs ലക്ഷ്യം',
    activeAlerts: '🔴 സജീവ അലേർട്ടുകൾ',
    viewAll: 'എല്ലാം കാണുക →',
    aiAgents: 'AI ഏജൻ്റുകൾ',
    aiAgentsSubtitle: 'ഫുൾ ഡാഷ്‌ബോർഡ് ആക്‌സസ് ചെയ്യാൻ ഏതെങ്കിലും ഏജൻ്റ് ക്ലിക്ക് ചെയ്യുക',
    agentActivityFeed: '⚡ ഏജൻ്റ് ആക്ടിവിറ്റി ഫീഡ്',
    fiveDayForecast: '🌤️ 5-ദിവസ പ്രവചനം',
    fullReport: 'പൂർണ്ണ റിപ്പോർട്ട് →',
    tappingAdvisory: '⚠️ ടാപ്പിംഗ് ഉപദേശം',
    tappingAdvisoryText: 'വെള്ളി-ശനി ദിവസങ്ങളിൽ കനത്ത മഴ പ്രതീക്ഷിക്കുന്നു. രാവിലെ ടാപ്പിംഗ് നിർത്തിവയ്ക്കുക. ഞായർ പുനരാരംഭിക്കുക.',
    cropHealthAgent: 'വിള ആരോഗ്യ ഏജൻ്റ്',
    cropHealthDesc: 'അപ്‌ലോഡ് ചെയ്ത ഇല ഫോട്ടോകളിൽ CNN/ViT മോഡലുകൾ വഴി AI-ശക്തിയുള്ള രോഗ കണ്ടെത്തൽ',
    cropHealthStat: '98.2% കൃത്യത',
    resourceAgent: 'വിഭവ ഏജൻ്റ്',
    resourceDesc: 'സ്മാർട്ട് ജലസേചനം, വളം ഷെഡ്യൂളിംഗ് & മണ്ണ് ആരോഗ്യ ഒപ്റ്റിമൈസേഷൻ',
    resourceStat: '22% വെള്ളം ലാഭിച്ചു',
    weatherAgent: 'കാലാവസ്ഥ ഏജൻ്റ്',
    weatherDesc: 'മഴ പ്രവചനം, ടാപ്പിംഗ് ഷെഡ്യൂൾ & ജലസേചന ഉപദേശം',
    weatherStat: 'അടുത്ത മഴ: വെള്ളി',
    advisoryAgent: 'ഉപദേശ ഏജൻ്റ്',
    advisoryDesc: 'LLM + RAG ശക്തിയുള്ള ബഹുഭാഷ ചാറ്റ് - മലയാളം & ഇംഗ്ലീഷ്',
    advisoryStat: 'RAG ശക്തിയുള്ളത്',
    act1: 'ഉപദേശ ഏജൻ്റ് ബ്ലോക്ക് 4-ന് നൈട്രജൻ ടോപ്-ഡ്രസ്സിംഗ് ശുപാർശ ചെയ്തു',
    act2: 'റിസോഴ്‌സ് ഏജൻ്റ് ജലസേചനം ഒപ്റ്റിമൈസ് ചെയ്തു – ഇന്ന് 340L ലാഭിച്ചു',
    act3: 'RSS വില ₹178/കിലോ ആയി ഉയർന്നു – മാർക്കറ്റ് ഏജൻ്റ് അലേർട്ട്',
    act4: 'കാലാവസ്ഥ ഏജൻ്റ്: കനത്ത മഴ പ്രവചിക്കപ്പെട്ടു – ടാപ്പിംഗ് നിർത്തി',
    act5: 'സോൺ A-ൽ ക്രോപ്പ് ഹെൽത്ത് സ്‌കാൻ പൂർത്തിയായി – 3 മരങ്ങൾ ഫ്ലാഗ് ചെയ്തു',
    ago: 'മുൻപ്',
    zone1: 'സോൺ A – ബ്ലോക്ക് 3',
    zone2: 'സോൺ B – ബ്ലോക്ക് 7',
    zone3: 'സോൺ C – ബ്ലോക്ക് 1',
    disease1: 'പൊടിപ്പൂൺ രോഗം',
    disease2: 'ഇല കൊഴിയൽ രോഗം',
    disease3: 'പിങ്ക് രോഗം',
    high: 'ഉയർന്ന',
    medium: 'മധ്യഭരണ',
    low: 'കുറഞ്ഞ',
  },

  hi: {
    dashboard: 'डैशबोर्ड',
    cropHealth: 'फसल स्वास्थ्य',
    resources: 'संसाधन',
    advisory: 'सलाह',
    orchestration: 'ऑर्केस्ट्रेशन',
    evaluation: 'मूल्यांकन',
    edgeDeploy: 'एज डिप्लॉय',
    systemStatus: 'सिस्टम स्थिति',
    cropAI: 'फसल AI',
    marketFeed: 'बाजार फ़ीड',
    weatherAPI: 'मौसम API',
    ragEngine: 'RAG इंजन',
    selectLanguage: 'भाषा चुनें',
    liveDashboard: '🌿 लाइव डैशबोर्ड',
    commandCenter: 'कमांड सेंटर',
    dashboardSubtitle: 'रबर बागान के लिए मल्टी-एजेंट AI सिस्टम · तिरुवनंतपुरम, केरल',
    farmHealthScore: 'फार्म स्वास्थ्य स्कोर',
    totalTrees: 'कुल पेड़',
    totalTreesSub: 'उत्पादक क्षेत्र: 4.8 एकड़',
    dailyLatex: 'दैनिक लेटेक्स (किग्रा)',
    dailyLatexSub: 'लक्ष्य: 42 किग्रा/दिन',
    revenue: 'राजस्व (मार्च)',
    revenueSub: 'पिछला: ₹61,200',
    diseaseAlerts: 'रोग चेतावनी',
    diseaseAlertsSub: '2 सक्रिय, 1 हल',
    yieldPerformance: 'उपज प्रदर्शन',
    yieldSubtitle: 'किग्रा/दिन बनाम लक्ष्य',
    activeAlerts: '🔴 सक्रिय अलर्ट',
    viewAll: 'सभी देखें →',
    aiAgents: 'AI एजेंट',
    aiAgentsSubtitle: 'पूर्ण डैशबोर्ड एक्सेस के लिए किसी भी एजेंट पर क्लिक करें',
    agentActivityFeed: '⚡ एजेंट गतिविधि फ़ीड',
    fiveDayForecast: '🌤️ 5-दिन का पूर्वानुमान',
    fullReport: 'पूर्ण रिपोर्ट →',
    tappingAdvisory: '⚠️ टैपिंग सलाह',
    tappingAdvisoryText: 'शुक्रवार-शनिवार को भारी बारिश की उम्मीद। सुबह की टैपिंग बंद करें। रविवार को फिर शुरू करें।',
    cropHealthAgent: 'फसल स्वास्थ्य एजेंट',
    cropHealthDesc: 'CNN/ViT मॉडल के माध्यम से AI-संचालित रोग पहचान',
    cropHealthStat: '98.2% सटीकता',
    resourceAgent: 'संसाधन एजेंट',
    resourceDesc: 'स्मार्ट सिंचाई, उर्वरक शेड्यूलिंग और मृदा स्वास्थ्य अनुकूलन',
    resourceStat: '22% पानी बचाया',
    weatherAgent: 'मौसम एजेंट',
    weatherDesc: 'वर्षा पूर्वानुमान, टैपिंग शेड्यूल और सिंचाई सलाह',
    weatherStat: 'अगली बारिश: शुक्र',
    advisoryAgent: 'सलाह एजेंट',
    advisoryDesc: 'LLM + RAG संचालित बहुभाषी चैट - मलयालम और अंग्रेजी',
    advisoryStat: 'RAG संचालित',
    act1: 'सलाह एजेंट ने ब्लॉक 4 के लिए नाइट्रोजन टॉप-ड्रेसिंग की सिफारिश की',
    act2: 'संसाधन एजेंट ने सिंचाई अनुकूलित की – आज 340L बचाया',
    act3: 'RSS मूल्य ₹178/किग्रा हुआ – बाजार एजेंट अलर्ट',
    act4: 'मौसम एजेंट: भारी बारिश की भविष्यवाणी – टैपिंग बंद',
    act5: 'ज़ोन A में फसल स्वास्थ्य स्कैन पूर्ण – 3 पेड़ फ्लैग',
    ago: 'पहले',
    zone1: 'ज़ोन A – ब्लॉक 3',
    zone2: 'ज़ोन B – ब्लॉक 7',
    zone3: 'ज़ोन C – ब्लॉक 1',
    disease1: 'पाउडरी फफूंदी',
    disease2: 'पत्ती गिरने की बीमारी',
    disease3: 'गुलाबी रोग',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
  },

  ta: {
    dashboard: 'டாஷ்போர்டு',
    cropHealth: 'பயிர் ஆரோக்கியம்',
    resources: 'வளங்கள்',
    advisory: 'ஆலோசனை',
    orchestration: 'ஆர்கெஸ்ட்ரேஷன்',
    evaluation: 'மதிப்பீடு',
    edgeDeploy: 'எட்ஜ் டெப்லாய்',
    systemStatus: 'கணினி நிலை',
    cropAI: 'பயிர் AI',
    marketFeed: 'சந்தை ஊட்டம்',
    weatherAPI: 'வானிலை API',
    ragEngine: 'RAG இயந்திரம்',
    selectLanguage: 'மொழியை தேர்ந்தெடுக்கவும்',
    liveDashboard: '🌿 நேரடி டாஷ்போர்டு',
    commandCenter: 'கட்டளை மையம்',
    dashboardSubtitle: 'உங்கள் ரப்பர் தோட்டத்திற்கான பல-முகவர் AI அமைப்பு · திருவனந்தபுரம், கேரளா',
    farmHealthScore: 'பண்ணை சுகாதார மதிப்பெண்',
    totalTrees: 'மொத்த மரங்கள்',
    totalTreesSub: 'உற்பத்தி பரப்பு: 4.8 ஏக்கர்',
    dailyLatex: 'தினசரி லேடெக்ஸ் (கிலோ)',
    dailyLatexSub: 'இலக்கு: 42 கிலோ/நாள்',
    revenue: 'வருவாய் (மார்)',
    revenueSub: 'முந்தைய: ₹61,200',
    diseaseAlerts: 'நோய் எச்சரிக்கைகள்',
    diseaseAlertsSub: '2 செயலில், 1 தீர்க்கப்பட்டது',
    yieldPerformance: 'மகசூல் செயல்திறன்',
    yieldSubtitle: 'கிலோ/நாள் vs இலக்கு',
    activeAlerts: '🔴 செயலில் உள்ள எச்சரிக்கைகள்',
    viewAll: 'அனைத்தையும் காண்க →',
    aiAgents: 'AI முகவர்கள்',
    aiAgentsSubtitle: 'முழு டாஷ்போர்டை அணுக எந்த முகவரையும் கிளிக் செய்யவும்',
    agentActivityFeed: '⚡ முகவர் செயல்பாட்டு ஊட்டம்',
    fiveDayForecast: '🌤️ 5-நாள் முன்னறிவிப்பு',
    fullReport: 'முழு அறிக்கை →',
    tappingAdvisory: '⚠️ தட்டி ஆலோசனை',
    tappingAdvisoryText: 'வெள்ளி-சனி கனமழை எதிர்பார்க்கப்படுகிறது. காலை தட்டி நிறுத்தவும். ஞாயிறு மீண்டும் தொடங்கவும்.',
    cropHealthAgent: 'பயிர் சுகாதார முகவர்',
    cropHealthDesc: 'CNN/ViT மாதிரிகள் மூலம் AI-இயக்கும் நோய் கண்டுபிடிப்பு',
    cropHealthStat: '98.2% துல்லியம்',
    resourceAgent: 'வள முகவர்',
    resourceDesc: 'திறமையான நீர்ப்பாசனம், உர திட்டமிடல் மற்றும் மண் ஆரோக்கிய மேம்படுத்தல்',
    resourceStat: '22% நீர் சேமிப்பு',
    weatherAgent: 'வானிலை முகவர்',
    weatherDesc: 'மழை முன்னறிவிப்பு, தட்டி அட்டவணை மற்றும் நீர்ப்பாசன ஆலோசனை',
    weatherStat: 'அடுத்த மழை: வெள்ளி',
    advisoryAgent: 'ஆலோசனை முகவர்',
    advisoryDesc: 'LLM + RAG இயக்கும் பல மொழி அரட்டை - மலையாளம் மற்றும் ஆங்கிலம்',
    advisoryStat: 'RAG இயக்குகிறது',
    act1: 'ஆலோசனை முகவர் பிளாக் 4-க்கு நைட்ரஜன் மேல் உரம் பரிந்துரைத்தது',
    act2: 'வள முகவர் நீர்ப்பாசனம் மேம்படுத்தியது – இன்று 340L சேமிப்பு',
    act3: 'RSS விலை ₹178/கிலோ உயர்ந்தது – சந்தை முகவர் எச்சரிக்கை',
    act4: 'வானிலை முகவர்: கனமழை கணிக்கப்பட்டது – தட்டி நிறுத்தப்பட்டது',
    act5: 'மண்டலம் A-ல் பயிர் சுகாதார ஸ்கேன் முடிந்தது – 3 மரங்கள் கொடியிடப்பட்டன',
    ago: 'முன்பு',
    zone1: 'மண்டலம் A – பிளாக் 3',
    zone2: 'மண்டலம் B – பிளாக் 7',
    zone3: 'மண்டலம் C – பிளாக் 1',
    disease1: 'தூள் பூஞ்சை',
    disease2: 'இலை உதிர் நோய்',
    disease3: 'இளஞ்சிவப்பு நோய்',
    high: 'உயர்',
    medium: 'நடுத்தர',
    low: 'குறைவு',
  },

  te: {
    dashboard: 'డాష్‌బోర్డ్',
    cropHealth: 'పంట ఆరోగ్యం',
    resources: 'వనరులు',
    advisory: 'సలహా',
    orchestration: 'ఆర్కెస్ట్రేషన్',
    evaluation: 'మూల్యాంకనం',
    edgeDeploy: 'ఎడ్జ్ డిప్లాయ్',
    systemStatus: 'సిస్టమ్ స్థితి',
    cropAI: 'పంట AI',
    marketFeed: 'మార్కెట్ ఫీడ్',
    weatherAPI: 'వాతావరణ API',
    ragEngine: 'RAG ఇంజిన్',
    selectLanguage: 'భాష ఎంచుకోండి',
    liveDashboard: '🌿 లైవ్ డాష్‌బోర్డ్',
    commandCenter: 'కమాండ్ సెంటర్',
    dashboardSubtitle: 'మీ రబ్బరు తోటకు మల్టీ-ఏజెంట్ AI సిస్టమ్ · తిరువనంతపురం, కేరళ',
    farmHealthScore: 'ఫామ్ ఆరోగ్య స్కోర్',
    totalTrees: 'మొత్తం చెట్లు',
    totalTreesSub: 'ఉత్పాదక విస్తీర్ణం: 4.8 ఎకరాలు',
    dailyLatex: 'రోజువారీ లాటెక్స్ (కిలో)',
    dailyLatexSub: 'లక్ష్యం: 42 కిలో/రోజు',
    revenue: 'ఆదాయం (మార్)',
    revenueSub: 'గత: ₹61,200',
    diseaseAlerts: 'వ్యాధి హెచ్చరికలు',
    diseaseAlertsSub: '2 చురుకు, 1 పరిష్కరించబడ్డాయి',
    yieldPerformance: 'దిగుబడి పనితీరు',
    yieldSubtitle: 'కిలో/రోజు vs లక్ష్యం',
    activeAlerts: '🔴 చురుకైన హెచ్చరికలు',
    viewAll: 'అన్నీ చూడు →',
    aiAgents: 'AI ఏజెంట్లు',
    aiAgentsSubtitle: 'పూర్తి డాష్‌బోర్డ్ యాక్సెస్ కోసం ఏదైనా ఏజెంట్‌ని క్లిక్ చేయండి',
    agentActivityFeed: '⚡ ఏజెంట్ యాక్టివిటీ ఫీడ్',
    fiveDayForecast: '🌤️ 5-రోజుల అంచనా',
    fullReport: 'పూర్తి నివేదిక →',
    tappingAdvisory: '⚠️ ట్యాపింగ్ సలహా',
    tappingAdvisoryText: 'శుక్రవారం-శనివారం భారీ వర్షం అంచనా. ఉదయం ట్యాపింగ్ నిలిపివేయండి. ఆదివారం పునఃప్రారంభించండి.',
    cropHealthAgent: 'పంట ఆరోగ్య ఏజెంట్',
    cropHealthDesc: 'CNN/ViT మోడళ్ల ద్వారా AI-శక్తితో వ్యాధి గుర్తింపు',
    cropHealthStat: '98.2% ఖచ్చితత్వం',
    resourceAgent: 'వనరుల ఏజెంట్',
    resourceDesc: 'తెలివైన నీటిపారుదల, ఎరువుల షెడ్యూలింగ్ & నేల ఆరోగ్య ఆప్టిమైజేషన్',
    resourceStat: '22% నీరు ఆదా',
    weatherAgent: 'వాతావరణ ఏజెంట్',
    weatherDesc: 'వర్షపాత అంచనా, ట్యాపింగ్ షెడ్యూల్ & నీటిపారుదల సలహా',
    weatherStat: 'తదుపరి వర్షం: శుక్ర',
    advisoryAgent: 'సలహా ఏజెంట్',
    advisoryDesc: 'LLM + RAG శక్తితో బహుభాషా చాట్ - మళయాళం & ఇంగ్లీష్',
    advisoryStat: 'RAG శక్తి',
    act1: 'సలహా ఏజెంట్ బ్లాక్ 4 కోసం నత్రజని టాప్-డ్రెస్సింగ్ సూచించింది',
    act2: 'రిసోర్స్ ఏజెంట్ నీటిపారుదల ఆప్టిమైజ్ చేసింది – ఈరోజు 340L ఆదా',
    act3: 'RSS ధర ₹178/కిలో పెరిగింది – మార్కెట్ ఏజెంట్ హెచ్చరిక',
    act4: 'వాతావరణ ఏజెంట్: భారీ వర్షం అంచనా – ట్యాపింగ్ నిలిపివేయబడింది',
    act5: 'జోన్ A లో పంట ఆరోగ్య స్కాన్ పూర్తైంది – 3 చెట్లు ఫ్లాగ్',
    ago: 'ముందు',
    zone1: 'జోన్ A – బ్లాక్ 3',
    zone2: 'జోన్ B – బ్లాక్ 7',
    zone3: 'జోన్ C – బ్లాక్ 1',
    disease1: 'పౌడరీ మిల్డ్యూ',
    disease2: 'ఆకు రాలు వ్యాధి',
    disease3: 'పింక్ వ్యాధి',
    high: 'అధిక',
    medium: 'మధ్యస్థ',
    low: 'తక్కువ',
  },

  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    cropHealth: 'ಬೆಳೆ ಆರೋಗ್ಯ',
    resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    advisory: 'ಸಲಹೆ',
    orchestration: 'ಆರ್ಕೆಸ್ಟ್ರೇಶನ್',
    evaluation: 'ಮೌಲ್ಯಮಾಪನ',
    edgeDeploy: 'ಎಡ್ಜ್ ಡಿಪ್ಲಾಯ್',
    systemStatus: 'ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ',
    cropAI: 'ಬೆಳೆ AI',
    marketFeed: 'ಮಾರುಕಟ್ಟೆ ಫೀಡ್',
    weatherAPI: 'ಹವಾಮಾನ API',
    ragEngine: 'RAG ಎಂಜಿನ್',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    liveDashboard: '🌿 ನೇರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    commandCenter: 'ಕಮಾಂಡ್ ಸೆಂಟರ್',
    dashboardSubtitle: 'ನಿಮ್ಮ ರಬ್ಬರ್ ತೋಟಕ್ಕಾಗಿ ಮಲ್ಟಿ-ಏಜೆಂಟ್ AI ಸಿಸ್ಟಮ್ · ತಿರುವನಂತಪುರಂ, ಕೇರಳ',
    farmHealthScore: 'ಫಾರ್ಮ್ ಆರೋಗ್ಯ ಸ್ಕೋರ್',
    totalTrees: 'ಒಟ್ಟು ಮರಗಳು',
    totalTreesSub: 'ಉತ್ಪಾದಕ ವಿಸ್ತೀರ್ಣ: 4.8 ಎಕರೆ',
    dailyLatex: 'ದೈನಂದಿನ ಲೇಟೆಕ್ಸ್ (ಕಿಲೋ)',
    dailyLatexSub: 'ಗುರಿ: 42 ಕಿಲೋ/ದಿನ',
    revenue: 'ಆದಾಯ (ಮಾರ್)',
    revenueSub: 'ಹಿಂದಿನ: ₹61,200',
    diseaseAlerts: 'ರೋಗ ಎಚ್ಚರಿಕೆಗಳು',
    diseaseAlertsSub: '2 ಸಕ್ರಿಯ, 1 ಪರಿಹರಿಸಲಾಗಿದೆ',
    yieldPerformance: 'ಇಳುವರಿ ಕಾರ್ಯಕ್ಷಮತೆ',
    yieldSubtitle: 'ಕಿಲೋ/ದಿನ vs ಗುರಿ',
    activeAlerts: '🔴 ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು',
    viewAll: 'ಎಲ್ಲ ನೋಡಿ →',
    aiAgents: 'AI ಏಜೆಂಟ್‌ಗಳು',
    aiAgentsSubtitle: 'ಪೂರ್ಣ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಕ್ಕಾಗಿ ಯಾವುದೇ ಏಜೆಂಟ್ ಕ್ಲಿಕ್ ಮಾಡಿ',
    agentActivityFeed: '⚡ ಏಜೆಂಟ್ ಚಟುವಟಿಕೆ ಫೀಡ್',
    fiveDayForecast: '🌤️ 5-ದಿನ ಮುನ್ಸೂಚನೆ',
    fullReport: 'ಪೂರ್ಣ ವರದಿ →',
    tappingAdvisory: '⚠️ ಟ್ಯಾಪಿಂಗ್ ಸಲಹೆ',
    tappingAdvisoryText: 'ಶುಕ್ರವಾರ-ಶನಿವಾರ ಭಾರಿ ಮಳೆ ನಿರೀಕ್ಷಿತ. ಬೆಳಿಗ್ಗೆ ಟ್ಯಾಪಿಂಗ್ ತಡೆಹಿಡಿಯಿರಿ. ಭಾನುವಾರ ಮರುಪ್ರಾರಂಭಿಸಿ.',
    cropHealthAgent: 'ಬೆಳೆ ಆರೋಗ್ಯ ಏಜೆಂಟ್',
    cropHealthDesc: 'CNN/ViT ಮಾದರಿಗಳ ಮೂಲಕ AI-ಚಾಲಿತ ರೋಗ ಪತ್ತೆ',
    cropHealthStat: '98.2% ನಿಖರತೆ',
    resourceAgent: 'ಸಂಪನ್ಮೂಲ ಏಜೆಂಟ್',
    resourceDesc: 'ಸ್ಮಾರ್ಟ್ ನೀರಾವರಿ, ಗೊಬ್ಬರ ವೇಳಾಪಟ್ಟಿ & ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಆಪ್ಟಿಮೈಸೇಶನ್',
    resourceStat: '22% ನೀರು ಉಳಿತಾಯ',
    weatherAgent: 'ಹವಾಮಾನ ಏಜೆಂಟ್',
    weatherDesc: 'ಮಳೆ ಮುನ್ಸೂಚನೆ, ಟ್ಯಾಪಿಂಗ್ ವೇಳಾಪಟ್ಟಿ & ನೀರಾವರಿ ಸಲಹೆ',
    weatherStat: 'ಮುಂದಿನ ಮಳೆ: ಶುಕ್ರ',
    advisoryAgent: 'ಸಲಹೆ ಏಜೆಂಟ್',
    advisoryDesc: 'LLM + RAG ಚಾಲಿತ ಬಹುಭಾಷಾ ಚಾಟ್ - ಮಲಯಾಳಂ & ಇಂಗ್ಲೀಷ್',
    advisoryStat: 'RAG ಚಾಲಿತ',
    act1: 'ಸಲಹೆ ಏಜೆಂಟ್ ಬ್ಲಾಕ್ 4 ಗೆ ನೈಟ್ರೋಜನ್ ಟಾಪ್-ಡ್ರೆಸ್ಸಿಂಗ್ ಶಿಫಾರಸು ಮಾಡಿದೆ',
    act2: 'ರಿಸೋರ್ಸ್ ಏಜೆಂಟ್ ನೀರಾವರಿ ಆಪ್ಟಿಮೈಸ್ ಮಾಡಿದೆ – ಇಂದು 340L ಉಳಿತಾಯ',
    act3: 'RSS ಬೆಲೆ ₹178/ಕಿಲೋಗೆ ಏರಿತು – ಮಾರುಕಟ್ಟೆ ಏಜೆಂಟ್ ಎಚ್ಚರಿಕೆ',
    act4: 'ಹವಾಮಾನ ಏಜೆಂಟ್: ಭಾರಿ ಮಳೆ ಮುನ್ಸೂಚಿಸಲಾಗಿದೆ – ಟ್ಯಾಪಿಂಗ್ ತಡೆಹಿಡಿಯಲಾಗಿದೆ',
    act5: 'ವಲಯ A ನಲ್ಲಿ ಬೆಳೆ ಆರೋಗ್ಯ ಸ್ಕ್ಯಾನ್ ಪೂರ್ಣ – 3 ಮರಗಳು ಫ್ಲ್ಯಾಗ್',
    ago: 'ಹಿಂದೆ',
    zone1: 'ವಲಯ A – ಬ್ಲಾಕ್ 3',
    zone2: 'ವಲಯ B – ಬ್ಲಾಕ್ 7',
    zone3: 'ವಲಯ C – ಬ್ಲಾಕ್ 1',
    disease1: 'ಪೌಡರಿ ಮಿಲ್ಡ್ಯೂ',
    disease2: 'ಎಲೆ ಉದುರುವಿಕೆ ರೋಗ',
    disease3: 'ಪಿಂಕ್ ರೋಗ',
    high: 'ಹೆಚ್ಚು',
    medium: 'ಮಧ್ಯಮ',
    low: 'ಕಡಿಮೆ',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang] || translations['en'];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
